# Generated by Django 5.0.14 on 2026-05-20 03:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='Untitled Analysis', max_length=500)),
                ('input_text', models.TextField(blank=True)),
                ('input_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('input_type', models.CharField(choices=[('text', 'Pasted Text'), ('pdf', 'PDF File'), ('docx', 'Word File')], default='text', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('extracting', 'Extracting Citations'), ('analyzing', 'Analyzing Context'), ('verifying', 'Verifying Sources'), ('detecting', 'Detecting Hallucinations'), ('reporting', 'Generating Report'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analysis',
                'verbose_name_plural': 'Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_logs', to='detector.analysis')),
            ],
            options={
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('total_citations', models.IntegerField(default=0)),
                ('verified_citations', models.IntegerField(default=0)),
                ('questionable_citations', models.IntegerField(default=0)),
                ('hallucinated_citations', models.IntegerField(default=0)),
                ('overall_credibility_score', models.FloatField(default=0.0)),
                ('agent_logs', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='detector.analysis')),
            ],
            options={
                'verbose_name': 'Analysis Report',
                'verbose_name_plural': 'Analysis Reports',
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation_text', models.TextField()),
                ('context_before', models.TextField(blank=True)),
                ('context_after', models.TextField(blank=True)),
                ('claimed_source', models.CharField(blank=True, max_length=500)),
                ('claimed_year', models.IntegerField(blank=True, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('severity', models.CharField(choices=[('green', 'Verified'), ('yellow', 'Questionable'), ('red', 'Hallucinated')], default='yellow', max_length=10)),
                ('explanation', models.TextField(blank=True)),
                ('suggestion', models.TextField(blank=True)),
                ('is_hallucinated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='detector.analysis')),
            ],
            options={
                'verbose_name': 'Citation',
                'verbose_name_plural': 'Citations',
                'ordering': ['-confidence_score'],
            },
        ),
    ]
